[package]
name = "kobo-verses"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
kobo-image = { path = "../../crates/kobo-image" }
kobo-sdk = { path = "../../crates/kobo-sdk" }
kobo-ui = { path = "../../crates/kobo-ui" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[lints]
workspace = true
