//! Small offline word squares; clue numbering follows ordinary crossword order.
use std::collections::VecDeque;

pub const HISTORY: usize = 32;
pub struct Puzzle {
    pub id: &'static str,
    pub title: &'static str,
    pub level: &'static str,
    pub side: usize,
    pub answer: &'static [u8],
    pub across: &'static [&'static str],
    pub down: &'static [&'static str],
}
/// One numbered entry in a grid: where it starts, which way it reads, and how
/// many squares it covers.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct Entry {
    pub number: usize,
    pub down: bool,
    pub first: usize,
    pub length: usize,
}

pub const PUZZLES: &[Puzzle] = &[
    Puzzle {
        id: "cat-v1",
        title: "Small beginnings",
        level: "Word square",
        side: 3,
        answer: b"CATARETEN",
        across: &[
            "Pet that purrs",
            "Present form of ‘be’, with ‘you’",
            "Number of fingers on two hands",
        ],
        down: &[
            "Animal with whiskers and a meow",
            "‘We ___ ready’",
            "Two more than eight",
        ],
    },
    Puzzle {
        id: "ball-v1",
        title: "In the square",
        level: "Word square",
        side: 4,
        answer: b"BALLAREALEADLADY",
        across: &[
            "Round object used in many games",
            "Amount of surface covered",
            "Go first and show the way",
            "Woman addressed politely",
        ],
        down: &[
            "Formal dance, or something to throw",
            "Length times width, for a rectangle",
            "Be in front of the others",
            "Word paired with ‘gentleman’",
        ],
    },
    Puzzle {
        id: "heart-v1",
        title: "Heart of the matter",
        level: "Word square",
        side: 5,
        answer: b"HEARTEMBERABUSERESINTREND",
        across: &[
            "Organ that pumps blood",
            "A glowing coal",
            "Treat badly",
            "Sticky substance from a pine tree",
            "General direction of change",
        ],
        down: &[
            "‘Learn by ___’: memorize",
            "Last glowing piece of a fire",
            "Mistreatment",
            "Amber began as this tree substance",
            "A fashion that is gaining followers",
        ],
    },
    Puzzle {
        id: "mini-v1",
        title: "Odds and ends",
        level: "Crossword",
        side: 5,
        // Generated by tools/crossword/generate.py from the clue table, which
        // is why no answer appears twice here. What it replaced was a grid
        // with two by two blocks of black squares in its corners, which no
        // paper prints, and which existed only because the old model could
        // not express more than one entry per row.
        answer: b"#PUT#MINORALIKENOTED#TEN#",
        across: &[
            "Place down",
            "Lesser of two",
            "Much the same",
            "Well known",
            "Fingers on two hands",
        ],
        down: &[
            "Flies the plane",
            "Bring together",
            "Small sign of it",
            "Grown male",
            "Colour of a stop light",
        ],
    },
];
impl Puzzle {
    /// Every square that begins an entry, in the order a grid numbers them.
    ///
    /// A square starts an entry when the run it belongs to begins there and is
    /// long enough to be one, which is what a printed grid numbers.
    fn starts(&self, cell: usize) -> bool {
        if self.answer[cell] == b'#' {
            return false;
        }
        self.run(cell, false).first() == Some(&cell) || self.run(cell, true).first() == Some(&cell)
    }

    pub fn number(&self, cell: usize) -> Option<usize> {
        if !self.starts(cell) {
            return None;
        }
        Some((0..=cell).filter(|other| self.starts(*other)).count())
    }

    /// The squares of the entry `cell` belongs to, in one direction.
    ///
    /// A contiguous run, stopping at a black square rather than skipping it.
    /// The whole row minus its black squares used to be treated as one word,
    /// so two entries either side of a black square were one entry as far as
    /// entering letters was concerned, and a grid could only ever hold one
    /// entry per row and one per column. That is the whole reason the only
    /// puzzle with black squares had to put them in the corners.
    pub fn run(&self, cell: usize, down: bool) -> Vec<usize> {
        if self.answer[cell] == b'#' {
            return Vec::new();
        }
        let step = if down { self.side } else { 1 };
        let row = cell / self.side;
        let mut first = cell;
        while first >= step
            && self.answer[first - step] != b'#'
            && (down || (first - step) / self.side == row)
        {
            first -= step;
        }
        let mut cells = vec![first];
        let mut next = first;
        while next + step < self.answer.len()
            && self.answer[next + step] != b'#'
            && (down || (next + step) / self.side == row)
        {
            next += step;
            cells.push(next);
        }
        cells
    }

    /// Kept for the screens that ask for a word by one of its squares.
    pub fn word(&self, selected: usize, down: bool) -> Vec<usize> {
        let run = self.run(selected, down);
        if run.len() > 1 {
            return run;
        }
        // A square with no entry in this direction keeps the other one, so a
        // tap never lands on nothing.
        let other = self.run(selected, !down);
        if other.len() > 1 {
            other
        } else {
            run
        }
    }

    /// Every entry, numbered, in the order a printed clue list prints them.
    pub fn entries(&self) -> Vec<Entry> {
        let mut out = Vec::new();
        for cell in 0..self.answer.len() {
            let Some(number) = self.number(cell) else {
                continue;
            };
            for down in [false, true] {
                let run = self.run(cell, down);
                if run.len() > 1 && run[0] == cell {
                    out.push(Entry {
                        number,
                        down,
                        first: cell,
                        length: run.len(),
                    });
                }
            }
        }
        out.sort_by_key(|entry| (entry.number, entry.down));
        out
    }

    /// The clue for an entry, taken in the order the clues are written down.
    pub fn clue_of(&self, entry: &Entry) -> &'static str {
        let list = if entry.down { self.down } else { self.across };
        let position = self
            .entries()
            .iter()
            .filter(|other| other.down == entry.down)
            .position(|other| other.first == entry.first && other.number == entry.number)
            .unwrap_or(0);
        list.get(position).copied().unwrap_or("")
    }

    pub fn clue(&self, selected: usize, down: bool) -> (String, &'static str) {
        // The direction the square actually reads in, which is the one asked
        // for when it has an entry that way and the other when it does not.
        // Deriving it from the run rather than from the request is what stops
        // the line above the grid naming a word the grid is not highlighting.
        let down = if self.run(selected, down).len() > 1 {
            down
        } else {
            !down
        };
        let cells = self.run(selected, down);
        let first = cells.first().copied().unwrap_or(selected);
        let entry = self
            .entries()
            .into_iter()
            .find(|entry| entry.first == first && entry.down == down);
        match entry {
            Some(entry) => (
                format!(
                    "{} {}",
                    entry.number,
                    if entry.down { "Down" } else { "Across" }
                ),
                self.clue_of(&entry),
            ),
            None => (String::new(), ""),
        }
    }
}
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Position {
    pub letters: Vec<u8>,
    pub selected: usize,
    pub down: bool,
}
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Progress {
    pub position: Position,
    pub undo: VecDeque<Position>,
    /// Lifetime assistance counters are not erased by undo or restart.
    pub reveals: u32,
    pub checks: u32,
    pub solved_once: bool,
}
impl Progress {
    pub fn new(p: &Puzzle) -> Self {
        Self {
            position: Position {
                letters: p
                    .answer
                    .iter()
                    .map(|b| if *b == b'#' { b'#' } else { b'.' })
                    .collect(),
                // The first white square, which is not square zero once a grid
                // has black corners: starting on a black square left nothing
                // selected, refused the save that recorded it, and panicked
                // the moment a letter was entered.
                selected: p
                    .answer
                    .iter()
                    .position(|square| *square != b'#')
                    .unwrap_or(0),
                down: false,
            },
            undo: VecDeque::new(),
            reveals: 0,
            checks: 0,
            solved_once: false,
        }
    }
    pub fn solved(&self, p: &Puzzle) -> bool {
        self.position.letters == p.answer
    }
    pub fn remember(&mut self) {
        if self.undo.len() == HISTORY {
            self.undo.pop_front();
        }
        self.undo.push_back(self.position.clone());
    }
    pub fn enter(&mut self, p: &Puzzle, text: &str) -> Result<(), &'static str> {
        let word = p.word(self.position.selected, self.position.down);
        if word.is_empty()
            || !text.bytes().all(|b| b.is_ascii_alphabetic())
            || (text.len() != 1 && text.len() != word.len())
        {
            return Err("Enter one letter or the whole word.");
        }
        self.remember();
        if text.len() == 1 {
            self.position.letters[self.position.selected] = text.as_bytes()[0].to_ascii_uppercase();
            if let Some(n) = word.iter().position(|c| *c == self.position.selected) {
                self.position.selected = word[(n + 1).min(word.len() - 1)];
            }
        } else {
            for (cell, byte) in word.into_iter().zip(text.bytes()) {
                self.position.letters[cell] = byte.to_ascii_uppercase();
            }
        }
        self.solved_once |= self.solved(p);
        Ok(())
    }
    pub fn reveal(&mut self, p: &Puzzle) {
        let cell = self.position.selected;
        // Confirming an already-correct guess still reveals the answer.
        self.remember();
        self.position.letters[cell] = p.answer[cell];
        self.reveals = self.reveals.saturating_add(1);
        self.solved_once |= self.solved(p);
    }
    pub fn check(&mut self, p: &Puzzle) -> String {
        self.checks = self.checks.saturating_add(1);
        let word = p.word(self.position.selected, self.position.down);
        let empty = word
            .iter()
            .filter(|c| self.position.letters[**c] == b'.')
            .count();
        let wrong = word
            .iter()
            .filter(|c| {
                self.position.letters[**c] != b'.' && self.position.letters[**c] != p.answer[**c]
            })
            .count();
        if wrong == 0 && empty == 0 {
            "This word is correct.".into()
        } else {
            format!("{wrong} incorrect, {empty} empty. Your letters are unchanged.")
        }
    }
}
